print("guess a number vro")
number = input("Your number vro: ")
print("wrong number vro")
idiotNumber = input("try again vro: ")
print("jk")
print("Doh-hohohohoho!")
print("ok now try again")
realNumberFrThisTime = input("ok fr this time vro: ")
print("dumbass pumpkimg")
